# Generated by Django 3.2.9 on 2023-09-29 03:02

from django.db import migrations, models
import django.db.models.deletion
import knowledge_base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True, verbose_name='The Project')),
                ('challenges', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True, verbose_name='Our Solution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=knowledge_base.models.universal_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalGuideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_image', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.contentimage')),
                ('technical_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='knowledge_base.technicalguide')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_image', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='knowledge_base.casestudy')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.contentimage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
