# Generated by Django 3.2.9 on 2025-03-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_price_expiry'),
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='case_studies', to='products.Product'),
        ),
        migrations.AddField(
            model_name='technicalguide',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='technical_guides', to='products.Product'),
        ),
    ]
