# Generated by Django 3.2.9 on 2023-09-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
