# Generated by Django 3.2.9 on 2023-10-31 03:42

from django.db import migrations, models
import knowledge_base.models
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(storage=storage_backends.PublicMediaStorage(), upload_to=knowledge_base.models.universal_image_upload_path),
        ),
    ]
