# Generated by Django 3.2.9 on 2025-03-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_auto_20250317_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediarelation',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for SEO and accessibility.', max_length=255, null=True),
        ),
    ]
