# Generated by Django 3.2.9 on 2023-09-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_casestudy_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalguide',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='technicalguide',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
