# Generated by Django 3.2.9 on 2025-05-05 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_base', '0003_mediarelation_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalguide',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_guides', to=settings.AUTH_USER_MODEL),
        ),
    ]
