# Generated by Django 3.2.9 on 2023-10-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_auto_20230929_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='caption',
            field=models.CharField(default='', max_length=255),
        ),
    ]
