# Generated by Django 3.2.9 on 2023-10-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_casestudy_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
