# Generated by Django 3.2.9 on 2023-10-25 01:37

from django.db import migrations, models
import knowledge_base.models
import storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_contentimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='file',
            field=models.ImageField(storage=storage_backends.PublicMediaStorage(), upload_to=knowledge_base.models.universal_image_upload_path),
        ),
    ]
