# Generated by Django 3.2.9 on 2023-10-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0006_alter_contentimage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
