# Generated by Django 3.2.9 on 2023-10-27 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('knowledge_base', '0007_contentimage_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelImageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_main_image', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.contentimage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='technicalguideimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='technicalguideimage',
            name='technical_guide',
        ),
        migrations.DeleteModel(
            name='CaseStudyImage',
        ),
        migrations.DeleteModel(
            name='TechnicalGuideImage',
        ),
    ]
