# Generated by Django 3.2.9 on 2023-10-31 03:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='This is a short concise and useful description of the product')),
                ('long_description', models.TextField(blank=True, help_text='This is for SEO purposes')),
                ('notes', models.TextField(blank=True)),
                ('suppliers', models.CharField(blank=True, help_text='Please comma separate names', max_length=200)),
                ('unit_of_measure', models.CharField(choices=[('rolls', 'Rolls'), ('sqm', 'SQM')], default='rolls', max_length=200)),
                ('twentygp_cap', models.IntegerField(blank=True, default=0, null=True)),
                ('fortygp_cap', models.IntegerField(blank=True, default=0, null=True)),
                ('fortyhc_cap', models.IntegerField(blank=True, default=0, null=True)),
                ('moq', models.IntegerField(default=0, null=True)),
                ('alternative_names', models.CharField(blank=True, help_text='Please comma separate names', max_length=200)),
                ('packing_description', models.CharField(blank=True, max_length=200)),
                ('applications', models.ManyToManyField(blank=True, related_name='products', to='products.Application')),
            ],
        ),
        migrations.CreateModel(
            name='DrainageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(choices=[('strip', 'Strip Drain'), ('sheet', 'Sheet Drain')], max_length=200)),
                ('height', models.IntegerField(help_text='Unit of measure is mm')),
                ('roll_width', models.IntegerField(help_text='Unit of measure is mm')),
                ('double_cuspated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GCL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.IntegerField(help_text='Unit of measure is gsm')),
                ('roll_width', models.DecimalField(decimal_places=2, help_text='Unit of measure is m', max_digits=4)),
                ('roll_length', models.DecimalField(decimal_places=2, help_text='Unit of measure is m', max_digits=5)),
                ('bentonite_specs', models.CharField(blank=True, max_length=200)),
                ('sub_category', models.CharField(choices=[('powder', 'Powder'), ('granules', 'Granules')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Geocell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(help_text='Unit of measure is mm')),
                ('weld_spacing', models.IntegerField(help_text='Unit of measure is mm')),
                ('is_textured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Geogrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(choices=[('BI', 'BIAXIAL'), ('TRI', 'TRIAXIAL')], max_length=200)),
                ('strength_md', models.IntegerField(help_text='Strength in machine direction in kN')),
                ('strength_td', models.IntegerField(help_text='Strength in transverse direction in kN')),
            ],
        ),
        migrations.CreateModel(
            name='Geotextile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.IntegerField(help_text='Unit of measure is gsm')),
                ('roll_width', models.DecimalField(decimal_places=2, help_text='Unit of measure is m', max_digits=4)),
                ('roll_length', models.DecimalField(decimal_places=2, help_text='Unit of measure is m', max_digits=5)),
                ('sub_category', models.CharField(choices=[('woven', 'Woven'), ('nonwoven', 'Non-woven')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('existing_customer', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=15)),
                ('product_interested_in', models.CharField(max_length=200)),
                ('estimated_quantity', models.CharField(max_length=50)),
                ('specifications', models.TextField(blank=True)),
                ('project_based', models.TextField(blank=True)),
                ('needed_by', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product Enquiries',
            },
        ),
        migrations.CreateModel(
            name='ProductMediaRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], default='image', max_length=10)),
                ('resource_type', models.CharField(choices=[('datasheet', 'Datasheet'), ('brochure', 'Brochure'), ('installation_guide', 'Installation Guide'), ('accessory_guide', 'Accessory Guide'), ('test_report', 'Test Report')], max_length=255)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.media')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.baseproduct')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('qty', models.IntegerField()),
                ('unit_of_measure', models.CharField(choices=[('rolls', 'Rolls'), ('sqm', 'SQM')], default='sqm', max_length=200)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('FOB_port', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('aud', 'AUD')], default='usd', max_length=200)),
                ('expiry', models.DateField(blank=True, default=datetime.date(2023, 11, 30), null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.baseproduct')),
            ],
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='product_detail_drainage',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.drainageproduct'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='product_detail_gcl',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.gcl'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='product_detail_geocell',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.geocell'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='product_detail_geogrid',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.geogrid'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='product_detail_geotextile',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.geotextile'),
        ),
    ]
