# Generated by Django 3.2.9 on 2023-10-31 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmediarelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='products.baseproduct'),
        ),
        migrations.AlterField(
            model_name='productmediarelation',
            name='resource_type',
            field=models.CharField(choices=[('datasheet', 'Datasheet'), ('brochure', 'Brochure'), ('installation_guide', 'Installation Guide'), ('accessory_guide', 'Accessory Guide'), ('test_report', 'Test Report'), ('product_image', 'Product Image')], max_length=255),
        ),
    ]
