# Generated by Django 3.2.9 on 2021-11-19 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Geocells',
            new_name='Geocell',
        ),
    ]
