# Generated by Django 3.2.9 on 2023-12-01 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_price_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('geocell', 'Geocell'), ('geotextile', 'Geotextile'), ('gcl', 'GCL'), ('geogrid', 'Geogrid'), ('drainage', 'Drainage')], max_length=200),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='density',
            field=models.IntegerField(blank=True, help_text='Unit of measure is gsm, this is for geotextiles and GCL(Need to decide if this is for overall density or bentonite density)', null=True),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='heigth',
            field=models.IntegerField(blank=True, help_text='Unit of measure is mm, this is for geocells and drainage products', null=True),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='length',
            field=models.IntegerField(blank=True, help_text='Unit of measure is mm', null=True),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('strip', 'Drainage - Strip Drain'), ('sheet', 'Drainage - Sheet Drain'), ('powder', 'GCL - Powder'), ('granules', 'GCL - Granules'), ('biaxial', 'Geogrid - Biaxial'), ('triaxial', 'Geogrid - Triaxial'), ('composite', 'Geogrid - Composite Biaxial'), ('woven', 'Geotextiel - Woven'), ('nonwoven', 'Geotextile - Non-woven')], max_length=200),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='width',
            field=models.IntegerField(blank=True, help_text='Unit of measure is mm', null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 31), null=True),
        ),
    ]
