# Generated by Django 3.2.9 on 2021-11-19 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_geocells_geocell'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocell',
            name='is_textured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocell',
            name='weld_spacing',
            field=models.CharField(default=0, help_text='Unit of measure is mm', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('twentygp_cap', models.IntegerField(blank=True)),
                ('moq', models.IntegerField(blank=True)),
                ('product_detail_geocell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.geocell')),
            ],
        ),
    ]
