# Generated by Django 3.2.9 on 2021-11-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211119_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='supplier',
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='alternative_names',
            field=models.CharField(blank=True, help_text='Please comma separate names', max_length=200),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='fortygp_cap',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='fortyhc_cap',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='images',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='our_datasheets',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='packing_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='packing_photos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='sample_testing_reports',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='supplier_datasheets',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='suppliers',
            field=models.CharField(blank=True, help_text='Please comma separate names', max_length=200),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='unit_of_measure',
            field=models.CharField(choices=[('rolls', 'Rolls'), ('sqm', 'SQM')], default='rolls', max_length=200),
        ),
    ]
