# Generated by Django 3.2.9 on 2023-12-06 01:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20231201_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 5), null=True),
        ),
        migrations.RenameModel(
            old_name='BaseProduct',
            new_name='Product',
        ),
        migrations.AlterField(
            model_name='price',
            name='base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productmediarelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='products.product'),
        ),
    ]
