# Generated by Django 3.2.9 on 2021-11-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211119_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='moq',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
