# Generated by Django 3.2.9 on 2021-11-29 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_baseproduct_moq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproduct',
            name='images',
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='our_datasheets',
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='packing_photos',
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='sample_testing_reports',
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='supplier_datasheets',
        ),
        migrations.CreateModel(
            name='TestingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='products/testing_reports/')),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testReports', to='products.baseproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='products/product_images/')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.baseproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DatasheetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='products/datasheets/')),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasheets', to='products.baseproduct')),
            ],
        ),
    ]
