# Generated by Django 3.2.9 on 2024-08-12 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231206_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='productenquiry',
            name='company',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product'),
        ),
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2024, 9, 11), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('geocell', 'Geocell'), ('geotextile', 'Geotextile'), ('gcl', 'GCL'), ('geogrid', 'Geogrid'), ('drainage', 'Drainage')], max_length=200),
        ),
    ]
