# Generated by Django 3.2.9 on 2021-11-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211129_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('cost', 'Cost'), ('rrp', 'RRP')], default='sale', max_length=200)),
                ('date', models.DateField()),
                ('unit_of_measure', models.CharField(choices=[('rolls', 'Rolls'), ('sqm', 'SQM')], default='rolls', max_length=200)),
                ('incoterm', models.CharField(choices=[('fob', 'FOB'), ('cif', 'CIF'), ('ddp', 'DDP')], default='cif', max_length=200)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('aud', 'AUD')], default='usd', max_length=200)),
                ('expiry', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
