# Generated by Django 3.2.9 on 2025-03-08 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240812_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 7), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('strip', 'Drainage - Strip Drain'), ('sheet', 'Drainage - Sheet Drain'), ('powder', 'GCL - Powder'), ('granules', 'GCL - Granules'), ('geomembrane', 'GCL - Geomembrane'), ('biaxial', 'Geogrid - Biaxial'), ('triaxial', 'Geogrid - Triaxial'), ('composite', 'Geogrid - Composite Biaxial'), ('woven', 'Geotextile - Woven'), ('nonwoven', 'Geotextile - Non-woven')], max_length=200),
        ),
    ]
