# Generated by Django 3.2.9 on 2021-11-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='base_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.baseproduct'),
            preserve_default=False,
        ),
    ]
