# Generated by Django 3.2.9 on 2025-03-20 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20250318_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmediarelation',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for SEO and accessibility.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 19), null=True),
        ),
    ]
