# Generated by Django 3.2.9 on 2025-05-05 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20250320_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 4), null=True),
        ),
    ]
