# Generated by Django 3.2.9 on 2021-12-05 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211201_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='fortygp_cap',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='fortyhc_cap',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='product_detail_geocell',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.geocell'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='twentygp_cap',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='geocell',
            name='height',
            field=models.IntegerField(help_text='Unit of measure is mm'),
        ),
        migrations.AlterField(
            model_name='geocell',
            name='weld_spacing',
            field=models.IntegerField(help_text='Unit of measure is mm'),
        ),
    ]
