# Generated by Django 3.2.9 on 2025-05-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20250505_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
