# Generated by Django 3.2.9 on 2021-12-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211205_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='product_detail_gcl',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.gcl'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='product_detail_geotextile',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.geotextile'),
        ),
    ]
