# Generated by Django 3.2.9 on 2021-12-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211205_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sheet', 'Sheet Drain'), ('strip', 'Strip Drain')], default='strip', help_text='FreDrain = Strip Drain, TerraDrain = Sheet Drain', max_length=200)),
                ('roll_width', models.DecimalField(decimal_places=2, help_text='Unit of measure is mm', max_digits=4)),
                ('height', models.IntegerField(help_text='Unit of measure is mm')),
                ('double_cuspated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Geogrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('BI', 'BIAXIAL'), ('TRI', 'TRIAXIAL')], max_length=200)),
                ('strength_md', models.IntegerField(help_text='Strength in machine direction in kN')),
                ('strength_td', models.IntegerField(help_text='Strength in transverse direction in kN')),
            ],
        ),
        migrations.RemoveField(
            model_name='geotextile',
            name='roll_width',
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='product_detail_drainage',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.drainage'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='product_detail_geogrid',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.geogrid'),
        ),
    ]
