# Generated by Django 3.2.9 on 2021-12-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20211205_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotextile',
            name='roll_width',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Unit of measure is m', max_digits=4),
            preserve_default=False,
        ),
    ]
