# Generated by Django 3.2.9 on 2021-12-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_geotextile_roll_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drainage',
            name='roll_width',
            field=models.IntegerField(help_text='Unit of measure is mm'),
        ),
        migrations.AlterField(
            model_name='drainage',
            name='type',
            field=models.CharField(choices=[('strip', 'Strip Drain'), ('sheet', 'Sheet Drain')], default='strip', help_text='FreDrain = Strip Drain, TerraDrain = Sheet Drain', max_length=200),
        ),
    ]
