# Generated by Django 3.2.9 on 2021-12-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20211205_2328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drainage',
            new_name='DrainageProduct',
        ),
    ]
