# Generated by Django 3.2.9 on 2023-05-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_rename_drainage_drainageproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcl',
            old_name='bentotite_specs',
            new_name='bentonite_specs',
        ),
    ]
