# Generated by Django 3.2.9 on 2023-06-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_rename_bentotite_specs_gcl_bentonite_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
