# Generated by Django 3.2.9 on 2023-09-05 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20230606_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='baseproduct',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='gcl',
            name='suggested_applications',
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='long_description',
            field=models.TextField(blank=True, help_text='This is for SEO purposes'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='short_description',
            field=models.TextField(blank=True, help_text='This is a short concise and useful description of the product'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='title',
            field=models.CharField(default='PLEASE ADD A TITLE', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefile',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('datasheet', 'Datasheet'), ('brochure', 'Brochure'), ('installation_guide', 'Installation Guide'), ('accessory_guide', 'Accessory Guide'), ('test_report', 'Test Report')], max_length=255)),
                ('file', models.FileField(upload_to='products/resources/')),
                ('description', models.TextField(blank=True)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='products.baseproduct')),
            ],
        ),
        migrations.CreateModel(
            name='GeotextileSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geogrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.geotextile')),
            ],
        ),
        migrations.CreateModel(
            name='GeogridSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geogrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.geogrid')),
            ],
        ),
        migrations.CreateModel(
            name='GeocellSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geocell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.geocell')),
            ],
        ),
        migrations.CreateModel(
            name='GCLSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geocell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gcl')),
            ],
        ),
        migrations.CreateModel(
            name='DrainageProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geogrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.drainageproduct')),
            ],
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='applications',
            field=models.ManyToManyField(related_name='products', to='products.Application'),
        ),
    ]
