# Generated by Django 3.2.9 on 2023-09-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20230905_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drainageproductsubcategory',
            old_name='geogrid',
            new_name='drainage_product',
        ),
        migrations.RenameField(
            model_name='gclsubcategory',
            old_name='geocell',
            new_name='gcl',
        ),
        migrations.RenameField(
            model_name='geotextilesubcategory',
            old_name='geogrid',
            new_name='geotextile',
        ),
    ]
