# Generated by Django 3.2.9 on 2023-09-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20230905_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainageproduct',
            name='DrainageProductSubcategory',
            field=models.ManyToManyField(to='products.DrainageProductSubcategory'),
        ),
    ]
