# Generated by Django 3.2.9 on 2023-09-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_drainageproduct_drainageproductsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingfile',
            name='datasheet',
        ),
        migrations.RenameField(
            model_name='imagefile',
            old_name='image',
            new_name='product',
        ),
        migrations.AddField(
            model_name='imagefile',
            name='is_for_website',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DatasheetFile',
        ),
        migrations.DeleteModel(
            name='TestingFile',
        ),
    ]
