# Generated by Django 3.2.9 on 2023-09-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20230923_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geotextile',
            name='type',
        ),
        migrations.AddField(
            model_name='geotextile',
            name='sub_cat',
            field=models.CharField(choices=[('woven', 'Woven'), ('nonwoven', 'Non-woven')], default='woven', max_length=200),
            preserve_default=False,
        ),
    ]
