# Generated by Django 3.2.9 on 2023-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20230923_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geogrid',
            old_name='shape',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='geotextile',
            old_name='sub_cat',
            new_name='sub_category',
        ),
        migrations.RemoveField(
            model_name='drainageproduct',
            name='type',
        ),
        migrations.AddField(
            model_name='drainageproduct',
            name='sub_category',
            field=models.CharField(choices=[('strip', 'Strip Drain'), ('sheet', 'Sheet Drain')], default='strip', max_length=200),
            preserve_default=False,
        ),
    ]
