# Generated by Django 3.2.9 on 2023-09-27 00:28

import datetime
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20230923_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='location',
            new_name='FOB_port',
        ),
        migrations.RemoveField(
            model_name='price',
            name='incoterm',
        ),
        migrations.RemoveField(
            model_name='price',
            name='type',
        ),
        migrations.AddField(
            model_name='price',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.ImageField(upload_to=products.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 27), null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='unit_of_measure',
            field=models.CharField(choices=[('rolls', 'Rolls'), ('sqm', 'SQM')], default='sqm', max_length=200),
        ),
    ]
