# Generated by Django 3.2.9 on 2023-09-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20230927_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gclsubcategory',
            name='gcl',
        ),
        migrations.RemoveField(
            model_name='geocellsubcategory',
            name='geocell',
        ),
        migrations.RemoveField(
            model_name='geogridsubcategory',
            name='geogrid',
        ),
        migrations.RemoveField(
            model_name='geotextilesubcategory',
            name='geotextile',
        ),
        migrations.RemoveField(
            model_name='drainageproduct',
            name='DrainageProductSubcategory',
        ),
        migrations.AddField(
            model_name='gcl',
            name='sub_category',
            field=models.CharField(choices=[('powder', 'Powder'), ('granules', 'Granules')], default='granules', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DrainageProductSubcategory',
        ),
        migrations.DeleteModel(
            name='GCLSubcategory',
        ),
        migrations.DeleteModel(
            name='GeocellSubcategory',
        ),
        migrations.DeleteModel(
            name='GeogridSubcategory',
        ),
        migrations.DeleteModel(
            name='GeotextileSubcategory',
        ),
    ]
