# Generated by Django 3.2.9 on 2023-09-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20230927_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='qty',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
