# Generated by Django 3.2.9 on 2023-09-28 02:01

import datetime
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_price_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productresource',
            old_name='type',
            new_name='resource_type',
        ),
        migrations.RemoveField(
            model_name='productresource',
            name='file',
        ),
        migrations.AddField(
            model_name='productresource',
            name='resource_file',
            field=models.FileField(default='test', upload_to=products.models.resource_file_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 28), null=True),
        ),
    ]
