# Generated by Django 3.2.9 on 2023-10-05 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_price_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('existing_customer', models.BooleanField(default=False)),
                ('product_interested_in', models.CharField(max_length=200)),
                ('estimated_quantity', models.CharField(max_length=50)),
                ('specifications', models.TextField(blank=True)),
                ('project_based', models.TextField(blank=True)),
                ('needed_by', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 4), null=True),
        ),
    ]
