# Generated by Django 3.2.9 on 2023-10-11 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20231005_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenquiry',
            name='existing_customer',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=15),
        ),
    ]
