# Generated by Django 3.2.9 on 2023-10-12 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20231011_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 11), null=True),
        ),
    ]
