# Generated by Django 3.2.9 on 2023-10-27 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_price_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 26), null=True),
        ),
    ]
