# Generated by Django 3.2.9 on 2023-10-30 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0008_auto_20231027_0220'),
        ('products', '0040_alter_price_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModelImageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_image', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.contentimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.baseproduct')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='price',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 29), null=True),
        ),
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
