# Generated by Django 3.2.9 on 2023-10-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20231030_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodelimagerelation',
            old_name='is_main_image',
            new_name='is_default',
        ),
    ]
